# Generated by Django 5.1.4 on 2025-01-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_losses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oillossrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Запись о потере нефти', 'verbose_name_plural': 'Записи о потерях нефти'},
        ),
        migrations.AddField(
            model_name='oillossrecord',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='oillossrecord',
            name='oil_type',
            field=models.CharField(choices=[('Light', 'Лёгкая нефть'), ('Heavy', 'Тяжёлая нефть'), ('Gasoline', 'Бензин'), ('Diesel', 'Дизельное топливо')], max_length=100, verbose_name='Тип нефти или нефтепродукта'),
        ),
    ]
