# Generated by Django 5.1.4 on 2025-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_losses', '0005_densitydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuellosscalculation',
            name='calculated_loss',
        ),
        migrations.AddField(
            model_name='fuellosscalculation',
            name='calculated_loss_closed',
            field=models.FloatField(blank=True, null=True, verbose_name='Потери при закрытой струе (кг)'),
        ),
        migrations.AddField(
            model_name='fuellosscalculation',
            name='calculated_loss_combined',
            field=models.FloatField(blank=True, null=True, verbose_name='Потери при комбинированном наливе (кг)'),
        ),
        migrations.AddField(
            model_name='fuellosscalculation',
            name='calculated_loss_open',
            field=models.FloatField(blank=True, null=True, verbose_name='Потери при открытой струе (кг)'),
        ),
    ]
